### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by Benchwork** [windoze/esparrier-idf#7]
I found your repo because of the barrier repo, would you be willing to create a release version for the hardware you used? 

I am not as savvy as I would like, and it will take me a long time just to get the environment setup just to build it, however I would like to test this as it really would be helpful for me daily life.

**Comment by windoze** [comment]
Thanks for the feedback.

The ESP/Rust ecosystem is rapidly growing and far from stable, breaking changes may be introduced at anytime, some of them are already impacting this project, e.g. the recent IDF/Rust toolchain cannot compile IDF 4.4 anymore.

I'm working on transition to IDFv5 right now, will keep you posted when they're ready.

**Comment by windoze** [comment]
@Benchwork
After several attempts I finally decided to abandon this project, the `esp-idf-hal` crates are really not friendly to USB functionalities.
A new project based on baremetal `esp-hal` is created at [Esparrier](https://github.com/windoze/esparrier), which has most of features existing in this project, the only missing part is the clipboard support, and it will be added soon. You can check it out if you're interested.

This repo will be archived, no update will be made.

**Comment by Benchwork** [comment]
Thank you for the update and appreciate the attempt!  Will you be releasing a version on that one?

**Comment by windoze** [comment]
A release of Esparrier has been created at https://github.com/windoze/esparrier/releases/tag/v0.1.2

The doc about how to flash the binary and the configuration can be found at https://github.com/windoze/esparrier?tab=readme-ov-file#use-pre-built-binaries

This repo will be archived and no update will be made.
